### ISSUE TITLE
Long load times

### ISSUE THREAD

**Issue by SamoSlaus** [gflewis/sndml3#48]
When loading cmdb_ci table (aprox. 8 million records) it takes 72 hours to sync the table.
We are using following configuration: - {name: cmdb_ci, action: sync, partition: week, pagesize: 1000}

Is there a faster way to sync the data?

**Comment by gflewis** [comment]
I would avoid using "action: sync" for a table that large. I would use "action: update, since: last" instead. The "update" action will not handle deletes, but cmdb_ci records are rarely, if ever deleted. If you are are deleting cmdb_ci records then just run your 72 hour "sync" job 3 or 4 times a year to clean them out.
