### ISSUE TITLE
PROCESS: Expected X rows but processed Y rows

### ISSUE THREAD

**Issue by tilennipic4** [gflewis/sndml3#50]
I am trying to load our cmdb_ci table, which has around 11M records to load to the DB. We are now using multiple concurrent instances of the SNDML to load parts of the table. Each instance is also partitioned by week/day. The speed it loads is just fine, but when it finishes it does not load all the records, it loads just cca 8.7M records.

This is an example of our YAML file (there are more yaml files, the created parameter is just different):
```
metrics: Path\To\Metrics\File.metrics
tables:
- {name: cmdb_ci, target: cmdb_ci_load, pagesize: 500, action: insert, created: [2020-01-01, 2020-04-01], partition: day, threads: 64}
```

For random queries to the table we get the RestTableReader warning log:
```
22:11:03 WARN RestTableReader [pool-3-thread-17] cmdb_ci.D2023-12-15 PROCESS: Expected 26143 rows but processed 26119 rows
22:11:03 WARN DatePartitionedTableReader [pool-3-thread-17] cmdb_ci.D2023-12-15 FINISH: Expected 26143 rows but only processed 26119 rows
```
These warnings are also random on every running instance of SNDML.

I also get a random JsonRequest warning when there is a "Time limit exceeded" error in the response, This is an example of the query that triggers the error:
```
sys_created_on%3E%3D2023-11-19%5Esys_created_on%3C2023-11-20%5Esys_id%3E4fc2139287aa355007ff542bbbbb35ca%5EORDERBYsys_id
```

What can I do in this situation, so it loads all the records from the table, becasue just the majority is not enough for us.

**Comment by gflewis** [comment]
**Regarding the row count mismatches:**
This could mean that some process is deleting records while the job is running (_e.g._ a cleanup job), but it is unlikely. Most likely your issue is caused by an ACL or a Before Query Business Rule. The `cmdb_ci` class will have lots of sub-classes. Perhaps there is a custom sub-class to which you do not have access, or a Before Query Business Rule is blocking you from reading some of the records. 

**Regarding the timeout errors:** 
64 threads is a lot. It means that you are banging at the instance really hard. I am not surprised that you would get timeouts with 64 threads. My prediction is that if you reduce the number of threads to 3 that you will get fewer timeouts, and the job will finish almost as fast.

**Comment by tilennipic4** [comment]
Thank you, I will look into this and try with 3 threads
